extensions:
  health_check:
  oauth2client:
    client_id: ${env:ENTRA_CLIENT_ID}
    client_secret: ${env:ENTRA_CLIENT_SECRET}
    token_url: https://login.microsoftonline.com/${env:ENTRA_TENANT_ID}/oauth2/v2.0/token
    scopes:
      - ${env:ENTRA_CLIENT_ID}/.default

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/remote:
    endpoint: ${env:SERVER_URL}:4318
    auth:
      authenticator: oauth2client

  debug:
    verbosity: basic

processors:
  batch:

service:
  extensions: [health_check, oauth2client]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/remote]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/remote]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/remote]
